.PHONY: all

all: fig-2Dtri2.png fig-2Dtri1.png fig-2Dtri0.png fig-2Dtri3.png fig-1Dfam-00.png fig-1Dfam-01.png fig-1Dfam-02.png fig-1Dfam-03.png fig-1Dfam-04.png fig-1Dfam-05.png fig-1Dfam-06.png fig-1Dfam-07.png fig-cell-child1.png fig-cell-child2.png fig-cell-vert.png fig-cell-end.png fig-cell-grid2.png fig-cell-coords.png fig-cell-bdry2.png fig-cell-int2.png fig-cell-nbr0.png

MRPTree : MRPTree.cpp MRPTree.hpp 
	g++ -std=c++23 MRPTree.cpp -o MRPTree

fig-2Dtri0.pdf : fig-2Dtri0.tex
	rm -f fig-2Dtri0.pdf
	pdflatex fig-2Dtri0.tex

fig-2Dtri0.png : fig-2Dtri0.pdf 
	convert -density 100 -alpha Remove fig-2Dtri0.pdf fig-2Dtri0.png

fig-2Dtri1.pdf : fig-2Dtri1.tex
	rm -f fig-2Dtri1.pdf
	pdflatex fig-2Dtri1.tex

fig-2Dtri1.png : fig-2Dtri1.pdf 
	convert -density 100 -alpha Remove fig-2Dtri1.pdf fig-2Dtri1.png

fig-2Dtri2.pdf : fig-2Dtri2.tex
	rm -f fig-2Dtri2.pdf
	pdflatex fig-2Dtri2.tex

fig-2Dtri2.png : fig-2Dtri2.pdf 
	convert -density 100 -alpha Remove fig-2Dtri2.pdf fig-2Dtri2.png

fig-2Dtri3.pdf : fig-2Dtri3.tex
	rm -f fig-2Dtri3.pdf
	pdflatex fig-2Dtri3.tex

fig-2Dtri3.png : fig-2Dtri3.pdf 
	convert -density 100 -alpha Remove fig-2Dtri3.pdf fig-2Dtri3.png

fig-2Dfam.pdf : fig-2Dfam.tex
	rm -f fig-2Dfam.pdf
	pdflatex fig-2Dfam.tex

fig-2Dfam.png : fig-2Dfam.pdf 
	convert -density 100 -alpha Remove fig-2Dfam.pdf fig-2Dfam.png

fig-1Dfam-00.pdf : fig-1Dfam-00.tex
	rm -f fig-1Dfam-00.pdf
	pdflatex fig-1Dfam-00.tex

fig-1Dfam-00.png : fig-1Dfam-00.pdf 
	convert -density 100 -alpha Remove fig-1Dfam-00.pdf fig-1Dfam-00.png

fig-1Dfam-01.pdf : fig-1Dfam-01.tex
	rm -f fig-1Dfam-01.pdf
	pdflatex fig-1Dfam-01.tex

fig-1Dfam-01.png : fig-1Dfam-01.pdf 
	convert -density 101 -alpha Remove fig-1Dfam-01.pdf fig-1Dfam-01.png

fig-1Dfam-02.pdf : fig-1Dfam-02.tex
	rm -f fig-1Dfam-02.pdf
	pdflatex fig-1Dfam-02.tex

fig-1Dfam-02.png : fig-1Dfam-02.pdf 
	convert -density 102 -alpha Remove fig-1Dfam-02.pdf fig-1Dfam-02.png

fig-1Dfam-03.pdf : fig-1Dfam-03.tex
	rm -f fig-1Dfam-03.pdf
	pdflatex fig-1Dfam-03.tex

fig-1Dfam-03.png : fig-1Dfam-03.pdf 
	convert -density 103 -alpha Remove fig-1Dfam-03.pdf fig-1Dfam-03.png

fig-1Dfam-04.pdf : fig-1Dfam-04.tex
	rm -f fig-1Dfam-04.pdf
	pdflatex fig-1Dfam-04.tex

fig-1Dfam-04.png : fig-1Dfam-04.pdf 
	convert -density 104 -alpha Remove fig-1Dfam-04.pdf fig-1Dfam-04.png

fig-1Dfam-05.pdf : fig-1Dfam-05.tex
	rm -f fig-1Dfam-05.pdf
	pdflatex fig-1Dfam-05.tex

fig-1Dfam-05.png : fig-1Dfam-05.pdf 
	convert -density 105 -alpha Remove fig-1Dfam-05.pdf fig-1Dfam-05.png

fig-1Dfam-06.pdf : fig-1Dfam-06.tex
	rm -f fig-1Dfam-06.pdf
	pdflatex fig-1Dfam-06.tex

fig-1Dfam-06.png : fig-1Dfam-06.pdf 
	convert -density 106 -alpha Remove fig-1Dfam-06.pdf fig-1Dfam-06.png

fig-1Dfam-07.pdf : fig-1Dfam-07.tex
	rm -f fig-1Dfam-07.pdf
	pdflatex fig-1Dfam-07.tex

fig-1Dfam-07.png : fig-1Dfam-07.pdf 
	convert -density 107 -alpha Remove fig-1Dfam-07.pdf fig-1Dfam-07.png

fig-cell-child1.pdf : fig-cell-child1.tex
	rm -f fig-cell-child1.pdf
	pdflatex fig-cell-child1.tex

fig-cell-child1.png : fig-cell-child1.pdf 
	convert -density 107 -alpha Remove fig-cell-child1.pdf fig-cell-child1.png

fig-cell-child2.pdf : fig-cell-child2.tex
	rm -f fig-cell-child2.pdf
	pdflatex fig-cell-child2.tex

fig-cell-child2.png : fig-cell-child2.pdf 
	convert -density 107 -alpha Remove fig-cell-child2.pdf fig-cell-child2.png

fig-cell-vert.pdf : fig-cell-vert.tex
	rm -f fig-cell-vert.pdf
	pdflatex fig-cell-vert.tex

fig-cell-vert.png : fig-cell-vert.pdf 
	convert -density 107 -alpha Remove fig-cell-vert.pdf fig-cell-vert.png

fig-cell-end.pdf : fig-cell-end.tex
	rm -f fig-cell-end.pdf
	pdflatex fig-cell-end.tex

fig-cell-end.png : fig-cell-end.pdf 
	convert -density 107 -alpha Remove fig-cell-end.pdf fig-cell-end.png

fig-cell-grid2.pdf : fig-cell-grid2.tex
	rm -f fig-cell-grid2.pdf
	pdflatex fig-cell-grid2.tex

fig-cell-grid2.png : fig-cell-grid2.pdf 
	convert -density 107 -alpha Remove fig-cell-grid2.pdf fig-cell-grid2.png

fig-cell-coords.pdf : fig-cell-coords.tex
	rm -f fig-cell-coords.pdf
	pdflatex fig-cell-coords.tex

fig-cell-coords.png : fig-cell-coords.pdf 
	convert -density 107 -alpha Remove fig-cell-coords.pdf fig-cell-coords.png

fig-cell-bdry2.pdf : fig-cell-bdry2.tex
	rm -f fig-cell-bdry2.pdf
	pdflatex fig-cell-bdry2.tex

fig-cell-bdry2.png : fig-cell-bdry2.pdf 
	convert -density 107 -alpha Remove fig-cell-bdry2.pdf fig-cell-bdry2.png

fig-cell-int2.pdf : fig-cell-int2.tex
	rm -f fig-cell-int2.pdf
	pdflatex fig-cell-int2.tex

fig-cell-int2.png : fig-cell-int2.pdf 
	convert -density 107 -alpha Remove fig-cell-int2.pdf fig-cell-int2.png

fig-cell-nbr0.pdf : fig-cell-nbr0.tex
	rm -f fig-cell-nbr0.pdf
	pdflatex fig-cell-nbr0.tex

fig-cell-nbr0.png : fig-cell-nbr0.pdf 
	convert -density 107 -alpha Remove fig-cell-nbr0.pdf fig-cell-nbr0.png
