#ifndef CONFIG_H
#define CONFIG_H

#define MRPTREE_PROJECT_NAME  "@CMAKE_PROJECT_NAME@"

#define MRPTREE_CONFIG_DATE   "@MRPTREE_CONFIG_DATE@"
#define MRPTREE_CONFIG_OS     "@CMAKE_HOST_SYSTEM_VERSION@"
#define MRPTREE_CONFIG_CMVER  "@CMAKE_VERSION@"
#define MRPTREE_CONFIG_ARCH   "@CMAKE_HOST_SYSTEM_PROCESSOR@"
#define MRPTREE_CONFIG_ENDIAN "@CMAKE_CXX_BYTE_ORDER@"
#define MRPTREE_CONFIG_COMPID "@CMAKE_CXX_COMPILER_ID@"

#define MRPTREE_VERSION       "@MRPTree_VERSION@"
#define MRPTREE_VERSION_MAJOR @MRPTree_VERSION_MAJOR@
#define MRPTREE_VERSION_MINOR @MRPTree_VERSION_MINOR@
#define MRPTREE_VERSION_PATCH @MRPTree_VERSION_PATCH@
#define MRPTREE_VERSION_TWEAK @MRPTree_VERSION_TWEAK@
#define MRPTREE_VERSION_TAG   "v@MRPTree_VERSION@"
#define MRPTREE_VERSION_DATE  "@MRPTREE_VERSION_DATE@"

#define MRPTREE_FOUND_DOXYGEN @MRPTREE_FOUND_DOXYGEN@
#define MRPTREE_FOUND_BTEST   @MRPTREE_FOUND_BTEST@

#define MRPTREE_OPT_DOXYGEN   @MRPTREE_OPT_DOXYGEN@
#define MRPTREE_OPT_BTEST     @MRPTREE_OPT_BTEST@

#include <string>

std::string mrptree_version_string() { return std::string(MRPTREE_VERSION_TAG) + " -- " + std::string(MRPTREE_VERSION_DATE); }

int mrptree_version_major() { return MRPTREE_VERSION_MAJOR; }
int mrptree_version_minor() { return MRPTREE_VERSION_MINOR; }
int mrptree_version_patch() { return MRPTREE_VERSION_PATCH; }
int mrptree_version_tweak() { return MRPTREE_VERSION_TWEAK; }

#endif
