* =MRPTree= (MR 2^P Tree)

=MRPTree= is C++ library implementing a data structure that is a generalization of the quadtree/octree concept to any dimension.
  - This single data structure is capable of representing quadtree-like structures in any dimension -- with no code modifications.
  - The resulting code is both less complex and easier to use than traditional tree based data structures.
  - Many tree operations are transformed into simple integer manipulation, and thus are much faster than tree operations.

You can read more about the way the data structure works here: [[https://richmit.github.io/MRPTree/tree_theory/trees.html][2^P Tree Theory]]

Documentation for the library may be found here: [[https://www.mitchr.me/SS/MRPtree/doc-lib/autodocs/html/index.html][MRPTree API Documentation]]

* Learn More

 - [[https://richmit.github.io/MRPTree/QuickStart.html][Quick Start Guide]]
 - [[https://richmit.github.io/MRPTree/tree_theory/trees.html][Documentation about how data structure works]]
 - [[https://github.com/richmit/MRPTree/blob/main/examples][Simple examples]]
 - [[https://github.com/richmit/MRCellCplx3D][More complex examples]]
 - Doxygen documentation
   - [[https://www.mitchr.me/SS/MRPTree/doc-examples/autodocs/html/index.html][Examples]]
   - [[https://www.mitchr.me/SS/MRPTree/doc-lib/autodocs/html/index.html][Library]]

* Build & Test Notes

 - MSYS2 on Windows 11:
   - g++: (Rev3, Built by MSYS2 project) 14.1.0
   - clang: 18.1.6
   - cmake: 3.29.5
   - boost: 1.85.0-2 (For unit tests)
 - Debian 12.6
   - g++: (Debian 14-20240330-1) 14.0.1 20240330 (experimental) [master r14-9728-g6fc84f680d0]
   - cmake: 3.25.1
   - boost: 1.83
 - Windows 11
   - Microsoft Visual Studio Community 2022 Version 17.10.5
   - cmake: 3.29.5
   - boost: I haven't tried to integrate with boost yet!

* Progress Updates

Please see the [[https://richmit.github.io/MRPTree/changelog.html#pre-release-changelog][Pre-Release Changelog]].

--------------------

Have fun!!

-mitch
