# -*- Mode:Org; Coding:utf-8; fill-column:158 -*-
# ######################################################################################################################################################.H.S.##
# FILE:        QuickStart.org
#+TITLE:       MRPTree Quick Start
#+AUTHOR:      Mitch Richling
#+EMAIL:       http://www.mitchr.me/
#+DATE:        2024-08-20
#+DESCRIPTION: Minimal tutorial for getting started with MRPTree
#+KEYWORDS:    KEYWORDS FIXME
#+LANGUAGE:    en
#+OPTIONS:     num:t toc:nil \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:t skip:nil d:nil todo:t pri:nil H:5 p:t author:t html-scripts:nil 
#+SEQ_TODO:    TODO:NEW(t)                         TODO:WORK(w)    TODO:HOLD(h)    | TODO:FUTURE(f)   TODO:DONE(d)    TODO:CANCELED(c)
#+PROPERTY: header-args :eval never-export
#+HTML_HEAD: <style>body { width: 95%; margin: 2% auto; font-size: 18px; line-height: 1.4em; font-family: Georgia, serif; color: black; background-color: white; }</style>
#+HTML_HEAD: <style>body { min-width: 500px; max-width: 1024px; }</style>
#+HTML_HEAD: <style>h1,h2,h3,h4,h5,h6 { color: #A5573E; line-height: 1em; font-family: Helvetica, sans-serif; }</style>
#+HTML_HEAD: <style>h1,h2,h3 { line-height: 1.4em; }</style>
#+HTML_HEAD: <style>h1.title { font-size: 3em; }</style>
#+HTML_HEAD: <style>.subtitle { font-size: 0.6em; }</style>
#+HTML_HEAD: <style>h4,h5,h6 { font-size: 1em; }</style>
#+HTML_HEAD: <style>.org-src-container { border: 1px solid #ccc; box-shadow: 3px 3px 3px #eee; font-family: Lucida Console, monospace; font-size: 80%; margin: 0px; padding: 0px 0px; position: relative; }</style>
#+HTML_HEAD: <style>.org-src-container>pre { line-height: 1.2em; padding-top: 1.5em; margin: 0.5em; background-color: #404040; color: white; overflow: auto; }</style>
#+HTML_HEAD: <style>.org-src-container>pre:before { display: block; position: absolute; background-color: #b3b3b3; top: 0; right: 0; padding: 0 0.2em 0 0.4em; border-bottom-left-radius: 8px; border: 0; color: white; font-size: 100%; font-family: Helvetica, sans-serif;}</style>
#+HTML_HEAD: <style>pre.example { white-space: pre-wrap; white-space: -moz-pre-wrap; white-space: -o-pre-wrap; font-family: Lucida Console, monospace; font-size: 80%; background: #404040; color: white; display: block; padding: 0em; border: 2px solid black; }</style>
#+HTML_LINK_HOME: https://www.mitchr.me/
#+HTML_LINK_UP: https://github.com/richmit/MRPTree/
# ######################################################################################################################################################.H.E.##

#+ATTR_HTML: :border 2 solid #ccc :frame hsides :align center
| Copyright \copy {{{time(%Y)}}} Mitch Richling. All rights reserved. |

#+TOC: headlines 5

* *=MRPtree=* Quick Start
:PROPERTIES:
:CUSTOM_ID: intro
:END:

While *=MRPtree=* comes with some examples, they are /very/ basic -- perfect for the quadtree/octree expert just wanting to know how to get up and running.
For more sophisticated examples illustrating how to make use of quadtree/octree-type data structures, see the examples in the
[[https://github.com/richmit/MRCellCplx3D][*=MRCellCplx3D=*]] library.

* Building *=MRPtree=* Examples With =CMake=
:PROPERTIES:
:CUSTOM_ID: build-wcmake
:END:

A typical shell session to build the examples might look like this:

#+begin_src sh :exports code :eval never
git clone 'https://github.com/richmit/MRPTree.git' # First clone the repo
cd MRPTree                                         # Change directory into the repo
rm -rf build                                       # Remove any existing build directy
mkdir build                                        # Create a new build directy
cd build                                           # Chaned directory into the build directory
cmake -G 'MSYS Makefiles' ..                       # Configure build (in this example for Windows running MSYS2)
cmake --build . -t examples                        # Build the examples
./hello_world.exe                                  # Run the example (leave off the ".exe" on Linux/MacOS
#+end_src

* Building *=MRPtree=* Examples Without =CMake=
:PROPERTIES:
:CUSTOM_ID: build-wocmake
:END:

If you really don't want to use =cmake=, then this will get you started:

#+begin_src sh :exports code :eval never
git clone 'https://github.com/richmit/MRPTree.git'                                  # First clone the repo
cd MRPTree                                                                          # Change directory into the repo
rm -rf build                                                                        # Remove any existing build directy
mkdir build                                                                         # Create a new build directy
cd build                                                                            # Chaned directory into the build directory
cmake -G 'MSYS Makefiles' ..                                                        # Configure build (in this example for Windows running MSYS2)
g++ -m64 -std=gnu++23 -I ../lib hello_world_regular.cpp -o hello_world_regular.exe  # Build an example
./hello_world_regular.exe                                                           # Run the example
gnuplot ../examples/hello_world_regular.gp                                          # Plot the output with GNUplot
#+end_src

